name: Manual-NPM-Publish

on:
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: npm install

    # Optional: Build your package if necessary
    # - name: Build
    #   run: npm run build

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
